"""Windows Hello user-verification helper.

This module wraps the Windows ``UserConsentVerifier`` interop API using only
``ctypes``. On non-Windows platforms the functions can be imported and called,
but they raise ``RuntimeError`` because the API is unavailable.

A successful verification returns or persists a 32-byte salt. The salt can be
used as the KDF salt when deriving the master key (for example, from TPM
protected key material), so the master key can only be unlocked when both the
TPM secret and the user are present.
"""

import logging
import os
import stat
import sys
from pathlib import Path

from doctoragent.security.keytree import generate_salt
from doctoragent.security.win_helpers import _require_windows

logger = logging.getLogger(__name__)

SALT_FILE_NAME = "windows_hello.salt"
SALT_LEN = 32


class WindowsHelloError(RuntimeError):
    """Raised when Windows Hello verification fails or is unavailable."""


if sys.platform == "win32":
    import ctypes
    import ctypes.wintypes as wintypes
    from typing import Any

    # IID for IUserConsentVerifierInterop from the Windows SDK.
    _IID_IUSER_CONSENT_VERIFIER_INTEROP = (
        0x39E050C3,
        0x4E74,
        0x441A,
        (0x8D, 0xC0, 0xB8, 0x11, 0x04, 0xDF, 0x94, 0x9C),
    )

    # IID for IAsyncOperation<UserConsentVerificationResult>. This must match
    # the parameterized interface GUID generated by the Windows Runtime for the
    # enum result type. It is only used on Windows, so Linux tests are not
    # affected if the value is updated for a specific Windows SDK revision.
    _IID_IASYNC_OPERATION_USER_CONSENT_VERIFICATION_RESULT = (
        0x2D0F7985,
        0x9EE6,
        0x427C,
        (0xAA, 0xAA, 0xA9, 0xD7, 0x2C, 0xBF, 0xA8, 0x53),
    )

    # IID for IAsyncInfo, used to poll for completion.
    _IID_IASYNC_INFO = (
        0x00000036,
        0x0000,
        0x0000,
        (0xC0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46),
    )

    _RUNTIME_CLASS = "Windows.Security.Credentials.UI.UserConsentVerifier"

    class _GUID(ctypes.Structure):  # noqa: N801
        _fields_ = [
            ("Data1", wintypes.ULONG),
            ("Data2", wintypes.WORD),
            ("Data3", wintypes.WORD),
            ("Data4", wintypes.BYTE * 8),
        ]

    def _make_guid(
        iid: tuple[int, int, int, tuple[int, int, int, int, int, int, int, int]],
    ) -> _GUID:
        return _GUID(
            Data1=iid[0],
            Data2=iid[1],
            Data3=iid[2],
            Data4=(wintypes.BYTE * 8)(*iid[3]),
        )

    def _create_hstring(text: str) -> ctypes.c_void_p:
        """Create an HSTRING from a Python string."""
        hstr = ctypes.c_void_p()
        hr = ctypes.windll.combase.WindowsCreateString(text, len(text), ctypes.byref(hstr))  # type: ignore[attr-defined]
        if hr != 0:
            raise RuntimeError(f"WindowsCreateString failed with HRESULT 0x{hr:08X}")
        return hstr

    def _delete_hstring(hstr: ctypes.c_void_p) -> None:
        if hstr:
            ctypes.windll.combase.WindowsDeleteString(hstr)  # type: ignore[attr-defined]

    def _ro_initialize() -> None:
        """Initialize the Windows Runtime for the current thread."""
        # RO_INIT_MULTITHREADED == 1
        ro_init = ctypes.windll.combase.RoInitialize  # type: ignore[attr-defined]
        hr = ro_init(1)
        # S_OK (0) and S_FALSE (1) are both acceptable.
        if hr not in (0, 1):
            raise RuntimeError(f"RoInitialize failed with HRESULT 0x{hr:08X}")

    def _get_activation_factory(runtime_class: str, iid: _GUID) -> ctypes.c_void_p:
        """Return the activation factory for a WinRT runtime class."""
        hstr = _create_hstring(runtime_class)
        try:
            factory = ctypes.c_void_p()
            hr = ctypes.windll.combase.RoGetActivationFactory(  # type: ignore[attr-defined]
                hstr,
                ctypes.byref(iid),
                ctypes.byref(factory),
            )
            if hr != 0:
                raise RuntimeError(f"RoGetActivationFactory failed with HRESULT 0x{hr:08X}")
            return factory
        finally:
            _delete_hstring(hstr)

    def _get_vtable_method(ptr: ctypes.c_void_p, index: int) -> Any:
        """Return a callable for the vtable method at *index*."""
        vtable_ptr = ctypes.cast(ptr, ctypes.POINTER(ctypes.c_void_p)).contents
        vtable = ctypes.cast(vtable_ptr, ctypes.POINTER(ctypes.c_void_p))
        return ctypes.cast(vtable[index], ctypes.c_void_p)

    def _poll_async_status(async_op: ctypes.c_void_p) -> int:
        """Poll an IAsyncOperation until it completes and return the status."""
        # IAsyncInfo::get_Status is at vtable index 7 (IUnknown 3 + IInspectable 3 + 1).
        get_status_ptr = _get_vtable_method(async_op, 7)
        get_status = ctypes.CFUNCTYPE(
            wintypes.HRESULT,
            ctypes.c_void_p,
            ctypes.POINTER(wintypes.INT),
        )(get_status_ptr)

        status = wintypes.INT(0)
        for _ in range(5000):  # ~10 seconds with 2 ms sleeps
            hr = get_status(async_op, ctypes.byref(status))
            if hr != 0:
                raise RuntimeError(f"IAsyncInfo::get_Status failed with HRESULT 0x{hr:08X}")
            if status.value != 0:  # 0 == AsyncStatus::Started
                break
            ctypes.windll.kernel32.Sleep(2)  # type: ignore[attr-defined]
        return status.value

    def _get_async_result(async_op: ctypes.c_void_p) -> int:
        """Return the UserConsentVerificationResult from a completed async op."""
        # IAsyncOperation<T>::GetResults is at vtable index 13
        # (IUnknown 3 + IInspectable 3 + IAsyncInfo 5 + 2).
        get_results_ptr = _get_vtable_method(async_op, 13)
        get_results = ctypes.CFUNCTYPE(
            wintypes.HRESULT,
            ctypes.c_void_p,
            ctypes.POINTER(wintypes.INT),
        )(get_results_ptr)

        result = wintypes.INT(0)
        hr = get_results(async_op, ctypes.byref(result))
        if hr != 0:
            raise RuntimeError(f"IAsyncOperation::GetResults failed with HRESULT 0x{hr:08X}")
        return result.value

    def _release_iunknown(ptr: ctypes.c_void_p) -> None:
        if ptr:
            release_ptr = _get_vtable_method(ptr, 2)
            release = ctypes.CFUNCTYPE(wintypes.ULONG, ctypes.c_void_p)(release_ptr)
            release(ptr)

    def _verify_user_identity_winrt(message: str) -> bool:
        """Call the UserConsentVerifier interop API and return success."""
        _ro_initialize()

        interop_iid = _make_guid(_IID_IUSER_CONSENT_VERIFIER_INTEROP)
        async_iid = _make_guid(_IID_IASYNC_OPERATION_USER_CONSENT_VERIFICATION_RESULT)

        interop = _get_activation_factory(_RUNTIME_CLASS, interop_iid)
        hmsg = _create_hstring(message)
        async_op = ctypes.c_void_p()

        try:
            hwnd = ctypes.windll.kernel32.GetConsoleWindow()  # type: ignore[attr-defined]

            # IUserConsentVerifierInterop::RequestVerificationForWindowAsync is at vtable index 3.
            request_ptr = _get_vtable_method(interop, 3)
            request = ctypes.CFUNCTYPE(
                wintypes.HRESULT,
                ctypes.c_void_p,
                wintypes.HWND,
                ctypes.c_void_p,  # HSTRING
                ctypes.POINTER(_GUID),
                ctypes.POINTER(ctypes.c_void_p),
            )(request_ptr)

            hr = request(
                interop,
                hwnd,
                hmsg,
                ctypes.byref(async_iid),
                ctypes.byref(async_op),
            )
            if hr != 0:
                logger.warning("RequestVerificationForWindowAsync failed: 0x%08X", hr)
                return False

            status = _poll_async_status(async_op)
            if status == 2:  # Canceled
                return False
            if status == 3:  # Error
                return False

            result = _get_async_result(async_op)
            # UserConsentVerificationResult.Verified == 0
            return result == 0
        finally:
            _release_iunknown(async_op)
            _release_iunknown(interop)
            _delete_hstring(hmsg)

else:

    def _verify_user_identity_winrt(_message: str) -> bool:
        """Non-Windows placeholder: always raises RuntimeError."""
        _require_windows()
        raise RuntimeError("Windows Hello is only available on Windows")


def verify_user_identity(message: str = "Unlock DoctorAgent") -> bool:
    """Request Windows Hello verification.

    Returns ``True`` if the user was successfully verified (fingerprint, face,
    PIN, etc.), and ``False`` if verification failed, was cancelled, or is
    unavailable.

    On non-Windows platforms this delegates to the placeholder implementation,
    which raises ``RuntimeError``.
    """
    _require_windows()
    return _verify_user_identity_winrt(message)


def get_key_derivation_salt(
    storage_path: Path,
    message: str = "Unlock DoctorAgent",
) -> bytes:
    """Verify the user with Windows Hello and return the KDF salt.

    The salt is persisted next to *storage_path* (``windows_hello.salt``) so
    that successful verifications on later runs return the same salt. The
    master-key derivation therefore remains deterministic across restarts as
    long as Windows Hello verification succeeds.

    Raises:
        WindowsHelloError: if verification fails or is cancelled.
        RuntimeError: if called on a non-Windows platform.
    """
    if not _verify_user_identity_winrt(message):
        raise WindowsHelloError("Windows Hello verification failed or was cancelled")

    salt_path = storage_path.parent / SALT_FILE_NAME
    try:
        return salt_path.read_bytes()
    except FileNotFoundError:
        pass

    salt = generate_salt()
    storage_path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(
        salt_path,
        os.O_CREAT | os.O_EXCL | os.O_WRONLY,
        stat.S_IRUSR | stat.S_IWUSR,
    )
    # os.fdopen takes ownership of the file descriptor. Track ownership so we
    # only close the raw fd when fdopen has not yet (or could not) take over.
    fd_taken_over = False
    try:
        with os.fdopen(fd, "wb") as fh:
            fd_taken_over = True
            fh.write(salt)
    except Exception:
        if not fd_taken_over:
            os.close(fd)
        raise
    return salt
